# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Code/Xilinx17/zhujiaoshiyan/UART_SRAM/UART_SRAM.cache/wt [current_project]
set_property parent.project_path E:/Code/Xilinx17/zhujiaoshiyan/UART_SRAM/UART_SRAM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Code/Xilinx17/zhujiaoshiyan/UART_SRAM/UART_SRAM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/Code/Xilinx17/zhujiaoshiyan/UART_SRAM/UART_SRAM.srcs/sources_1/imports/new/Freqdivide.v
  E:/Code/Xilinx17/zhujiaoshiyan/UART_SRAM/UART_SRAM.srcs/sources_1/new/UART_brgenerator.v
  E:/Code/Xilinx17/zhujiaoshiyan/UART_SRAM/UART_SRAM.srcs/sources_1/imports/new/UART_sim.v
  E:/Code/Xilinx17/zhujiaoshiyan/UART_SRAM/UART_SRAM.srcs/sources_1/imports/new/sram_controller.v
  E:/Code/Xilinx17/zhujiaoshiyan/UART_SRAM/UART_SRAM.srcs/sources_1/imports/new/sram_read_test.v
  E:/Code/Xilinx17/zhujiaoshiyan/UART_SRAM/UART_SRAM.srcs/sources_1/imports/new/sram_test.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Code/Xilinx17/zhujiaoshiyan/UART_SRAM/UART_SRAM.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files E:/Code/Xilinx17/zhujiaoshiyan/UART_SRAM/UART_SRAM.srcs/constrs_1/new/constraints.xdc]


synth_design -top UART_SRAM -part xc7a35tcsg324-1


write_checkpoint -force -noxdef UART_SRAM.dcp

catch { report_utilization -file UART_SRAM_utilization_synth.rpt -pb UART_SRAM_utilization_synth.pb }
